---
- hosts: nodos
  gather_facts: true
  tasks:
   - name: Instalando IIS
     win_feature:
       name: "web-server"
       state: present
       restart: yes
       include_sub_features: yes
       include_management_tools: yes
