---
- hosts: localhost
# Retrieve and display the number of customers
  tasks:
   - name: Get count of total costumers
     community.general.xml:
       path: ~/challenge/customers.xml
       xpath: /customer/email
       count: yes
#       register: hits

#   - ansible.builtin.debug:
#       var: hits.count